### ISSUE TITLE
no exact match found for input address

### ISSUE THREAD

**Issue by sangeeth5320** [ralucas/node-zillow#11]
Hello i got **no exact match found for input address** all the times 
my question is how to pass or format the geocode results data to pass input in parameters .
Below code use google maps api geocode to get address . 
geocode results data i have _street_number,  route,  city, state, zipcode, country_

function geocodeLatLng(geocoder, map, infowindow,location) {
    var latlng = {lat: location.lat , lng: location.lng };
   **geocoder.geocode**({'location': latlng}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        if (results[1]) {
        // omitted codes regarding fetching values from results , don't worry i got the correct data       /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var parameters = {
         //**Question is here how to format the address component**
	  address: encodeURIComponent(**street_number+route+state+country**),
          citystatezip: city+state+zip 
	};
      	zillow.get('GetSearchResults', parameters)
	.then(function(data) {
	  results = data.response.results.result[0].zestimate[0].amount[0]["_"];
           console.log('zestimate amount');  
	   console.log(results); // **returns zestimate data when address in parameters is hard coded**
	  return results;
	})
     }

**Comment by ralucas** [comment]
Hi @sangeeth5320,
From the looks here, I would say the `address` should just be the number and the street.  You may also want to confirm the response you're getting is expected...And to see if you're getting an error you may want to check the `message` property of the results hash.  Hope this helps.

Richard

**Comment by sangeeth5320** [comment]
Thanks for feedback . I figured out myself as per the **geocode input data**
passing **street_number+route+state** is enough and suppose to be  the correct format 
for the address field
