### ISSUE TITLE
webpack + react + node-zillow

### ISSUE THREAD

**Issue by jalemieux** [ralucas/node-zillow#12]
Have you tried using the module along with webpack and react? i'm getting this obscur error when requiring the module:
`index_bundle.js:36577 Uncaught Error: define cannot be used indirectmodule.exports @`

**Comment by ralucas** [comment]
I haven't tested this module with webpack, so I'd have to look into that error.  I can get to it next weekend or I welcome a tested PR.  Thanks for bringing this up.
