### ISSUE TITLE
GetDeepSearchResults returns 410 error code

### ISSUE THREAD

**Issue by lucasjacks0n** [ralucas/node-zillow#25]
Zillow may be killing this api to the public, 410 gone error code now

**Comment by idoraz** [comment]
Looks like Zillow shut down their API:
https://twitter.com/zillow/status/1365418247949058048

**Comment by lucasjacks0n** [comment]
was able to get a workaround / build my own tool using endpoints https://www.zillow.com/cma-tool/get-zpid and https://www.zillow.com/graphql/

**Comment by particlep** [comment]
> was able to get a workaround / build my own tool using endpoints https://www.zillow.com/cma-tool/get-zpid and https://www.zillow.com/graphql/

How did you find the qraphql schema? Looks like introspection is turned off.
