### ISSUE TITLE
GetDeepSearchResults returning undefined

### ISSUE THREAD

**Issue by LoganArnett** [ralucas/node-zillow#7]
Hey, first off this wrapper is amazing so thank you for building such a useful tool. 

I have been tinkering around with a few of the calls and so far have been successful except for using the GetDeepSearchResults. 

```javascript
var params = {
              address: // 123+Fake+St,
              city: // Fake+Town,
              state: //Fake+State,
              zip: // 12345
          }
```

or
```javascript
var params = {
              address: // 123+Fake+St,
              citystatezip: // Fake+Town+Fake+State+12345
          }

zillow.callApi('GetDeepSearchResults', params)
			.then(function(data){
				console.log(data)
				//results = data.response[0].results[0].result[0];
				//return res.json(200, results);
			})
```

So far just trying to review the data to make sure that I have it and Im getting back undefined. Just curious to see if you had any insight into this and could offer any help.

Thanks

**Comment by LoganArnett** [comment]
Found the issue as it related to this PR: [f8238fb](https://github.com/ralucas/node-zillow/pull/4). I believe the NPM package may not be up to date on that SearchResults

**Comment by ralucas** [comment]
Hi Logan,
So, I tested this and it takes the following as parameters:

```
var params = {
  address: '101 Some St.',
  citystatezip: SomeCity + ', ' + SomeState + ' ' + ZipCode
```

Were you seeing any errors?  I'm going to look at improving this api and making it easier to handle the data.

Best,
Richard

**Comment by LoganArnett** [comment]
Hey Richard,

Thanks for getting back to, I found that in the API List file the `Searchresults:searchresults` for the GetDeepSearchResults call needed to be `SearchResults:searchresults` as found in the PR I mentioned above, not sure if that means the npm package isn't up to date or if I some how messed with that while setting up the wrapper

**Comment by ralucas** [comment]
Hi Logan,
Thanks for the catch!  Yes, it is a version issue.  I just updated it v0.0.5, use that one and let me know if things don't work.

Best,

Richard
