### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by imcmahon** [ralucas/node-zillow#9]
Seems like NPM still has the 0.5 version. Can you send 1.0.0 over there?

Thanks!

**Comment by ralucas** [comment]
Hi @imcmahon,
Absolutely!  Are you using the 1x version? 

Cheers!

Richard

**Comment by imcmahon** [comment]
Awesome, thanks!

I am, just upgraded from .5 to the 1x version a day or two ago just using the github url. Seems to be working well after a few tweaks - updated call format to the global .get and updated the success and error response formats.

**Comment by ralucas** [comment]
Cool!  Well, if you have any questions, don't hesitate to reach out.  

Best,
Richard
